CREATE TABLE COURSE_TBL(
	ID VARCHAR2(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(40),
	CREDIT NUMBER(6),
	LECTURER VARCHAR2(10),
	WEEK NUMBER(2),
	START_HOUR NUMBER(4),
	END_END NUMBER(4)
);

SELECT * FROM COURSE_TBL;

CREATE TABLE LECTURER_TBL(
	IDX NUMBER(6) NOT NULL PRIMARY KEY,
	NAME VARCHAR2(30),
	MAJOR VARCHAR2(30),
	FIELD VARCHAR2(30)
);

DROP TABLE LECTURER_TBL;

SELECT * FROM LECTURER_TBL;