SELECT ID, NAME, CREDIT, LECTURER, WEEK, START_HOUR, END_END FROM COURSE_TBL WHERE ID = ?;

SELECT COUNT(ID) FROM COURSE_TBL;

SELECT ID, c.NAME AS NAME, CREDIT, l.NAME AS LECTURER, WEEK, START_HOUR, END_END FROM COURSE_TBL c JOIN LECTURER_TBL l ON c.LECTURER = l.IDX ORDER BY ID;

INSERT INTO COURSE_TBL VALUES (?, ?, ?, ?, ?, ?, ?);

UPDATE COURSE_TBL SET ID = ?, NAME = ?, LECTURER = ?, CREDIT = ?, WEEK = ?, START_HOUR = ?, END_END = ? WHERE ID = ?;

DELETE FROM COURSE_TBL WHERE ID = ?;





-------------------------------

SELECT IDX, NAME, MAJOR, FIELD FROM LECTURER_TBL ORDER BY IDX;

SELECT IDX, NAME, MAJOR, FIELD FROM LECTURER_TBL WHERE IDX = ?;

INSERT INTO LECTURER_TBL VALUES (?, ?, ?, ?);

DELETE FROM LECTURER_TBL WHERE IDX = ?;